import Script from "next/script";
import * as Sentry from "@sentry/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export function generateMetadata(): Metadata {
  return {
    title: "IC Node Monitoring",
    description: "Generated by IC Node Monitoring",
    other: {
      ...Sentry.getTraceData(),
    },
  };
}

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet/dist/leaflet.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet.markerplayer/Leaflet.MarkerPlayer.css"
        />
      </head>
      <body className={inter.className}>
        <Script
          src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://unpkg.com/leaflet.markerplayer@latest"
          strategy="beforeInteractive"
        />
        {children}
      </body>
    </html>
  );
}
